CFLAGS := -static -static-libgcc -O3 -pthread -D_POSIX_C_SOURCE=200112
#CFLAGS := -g3 -pthread -D_POSIX_C_SOURCE=200112
CFLAGS := $(CFLAGS) -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
CFLAGS := $(CFLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels
LDFLAGS := -lm

MACROS := $(BASEDIR)/null_macros/c.m4.null.POSIX_BARRIER
M4 := m4 -s -Ulen -Uindex

x = *

ifeq ($(SYS), X86)
	CC := gcc-4.1
else
	CC := gcc
	SYS := out
endif

ifeq ($(SYS), ARM)
	CC := arm-linux-gnueabihf-gcc
else
	CC := gcc
	SYS := out
endif

$(TARGET).$(SYS): $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) -o $(TARGET).$(SYS) $(LDFLAGS)

clean:
	rm -rf *.c *.h *.o $(TARGET).$(SYS)

.SUFFIXES:
.SUFFIXES:	.o .c .C .h .H

.H.h:
	$(M4) $(MACROS) $*.H > $*.h

.C.c:
	$(M4) $(MACROS) $*.C > $*.c

.c.o:
	$(CC) -c $(CFLAGS) $*.c

.C.o:
	$(M4) $(MACROS) $*.C > $*.c
	$(CC) -c $(CFLAGS) $*.c
