#!/bin/sh

/u/gs3/leec/leec/Projects/MediaBench/SPIX/SHADE/src/alu -o pegwitenc.summary -- ../pegwit -e my.pub pgptest.plain pegwit.enc < encryption_junk >pegwitenc.shade

/u/gs3/leec/leec/Projects/MediaBench/SPIX/SHADE/src/alu -o pegwitdec.summary -- ../pegwit -d pegwit.enc pegwit.dec < my.sec >pegwitdec.shade

