#!/bin/sh
# Run gem5 ALPHA all arguments pass to the run script will be
# passed to the gem5 fs.py script except the first arg
# is the destination of the statistics

out_dir="$1"
shift;
~/Desktop/comp_arch_sims/gem5-stable/build/ALPHA/gem5.opt --outdir=$out_dir ~/Desktop/comp_arch_sims/gem5-stable/configs/example/fs.py --disk-image=linux-parsec-2-1-m5-with-test-inputs.img --kernel=vmlinux_2.6.27-gcc_4.3.4 "$@"
